general.import = [ "~/Themes/alacritty.toml"]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }
size = 12

[window]
padding.x = 4
padding.y = 4
decorations = "None"
opacity = 0.8

[terminal.shell]
program = "/bin/zsh"
args = ["-lc", "fastfetch; exec zsh"]
